//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koncertas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KoncertasEntities3 : DbContext
    {
        public KoncertasEntities3()
            : base("name=KoncertasEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atlikejas> Atlikejas { get; set; }
        public virtual DbSet<Autorius> Autorius { get; set; }
        public virtual DbSet<Daina> Daina { get; set; }
    }
}
